/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        'surface-tint': '#3a5f94',
        'tertiary-fixed-dim': '#88d982',
        'surface': '#f7f9fc',
        'inverse-primary': '#a7c8ff',
        'on-tertiary-container': '#5ead5c',
        'secondary-fixed-dim': '#afcbd8',
        'on-secondary-fixed-variant': '#304a55',
        'on-secondary-container': '#4e6874',
        'on-tertiary': '#ffffff',
        'secondary': '#48626e',
        'on-primary': '#ffffff',
        'on-tertiary-fixed-variant': '#005312',
        'on-primary-fixed': '#001b3c',
        'outline-variant': '#c3c6d1',
        'on-primary-container': '#799dd6',
        'secondary-fixed': '#cbe7f5',
        'primary-fixed': '#d5e3ff',
        'surface-container': '#eceef1',
        'primary-fixed-dim': '#a7c8ff',
        'on-surface-variant': '#43474f',
        'on-secondary': '#ffffff',
        'tertiary-container': '#003d0b',
        'surface-container-low': '#f2f4f7',
        'error-container': '#ffdad6',
        'surface-variant': '#e0e3e6',
        'inverse-surface': '#2d3133',
        'on-background': '#191c1e',
        'on-error-container': '#93000a',
        'background': '#f7f9fc',
        'surface-dim': '#d8dadd',
        'on-surface': '#191c1e',
        'error': '#ba1a1a',
        'secondary-container': '#cbe7f5',
        'surface-container-lowest': '#ffffff',
        'surface-container-highest': '#e0e3e6',
        'on-secondary-fixed': '#021f29',
        'tertiary-fixed': '#a3f69c',
        'on-tertiary-fixed': '#002204',
        'surface-bright': '#f7f9fc',
        'on-primary-fixed-variant': '#1f477b',
        'primary': '#001e40',
        'primary-container': '#003366',
        'outline': '#737780',
        'tertiary': '#002504',
        'inverse-on-surface': '#eff1f4',
        'on-error': '#ffffff',
        'surface-container-high': '#e6e8eb',
        'logo-orange': '#F26522',
        'logo-green': '#009444',
        'logo-red': '#ED1C24',
        'logo-blue': '#0071BC',
      },
      fontFamily: {
        headline: ["Manrope", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"],
      },
      borderRadius: {
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
    },
  },
  plugins: [],
}
